### ISSUE TITLE
Add a way to disable animations on mobile

### ISSUE THREAD

**Issue by urbgimtam** [ingram-projects/animxyz#45]
Thank you for a great library.

There's currently no way to disable animations on mobile?
On desktop is fine to have many animations, but on mobile sometimes its nice to have more control, and disable certain animations.

How could it be done?

**Comment by milesingrams** [comment]
If you want to disable all AnimXYZ animations on mobile you can use a media query to target all actively "animating" elements and turn animations off.

```css
@media (maxn-width: 480px) {
  .xyz-appear,
  .xyz-appear .xyz-nested,
  .xyz-appear .xyz-appear-nested,
  .xyz-out,
  .xyz-out .xyz-nested,
  .xyz-out .xyz-out-nested,
  .xyz-in,
  .xyz-in .xyz-nested,
  .xyz-in .xyz-in-nested {
    animation: none !important;
  }
}
```

I cant think of a more concise pure CSS way that wont affect non-xyz animations. If you are using the Vue or javascript library you can use javascript to conditionally render the `<XyzTransition>` and `<XyzTransitionGroup>` components on different screen sizes. Perhaps for these components we can have a special prop to turn them off.
